apiVersion: int.esa.yass/v1
kind: Experiment
metadata:
  name: example-experiment
  namespace: default
spec:
  experimentDefRef: example-experimentdef
  layoutDefRef: example-layout
  engineContainers:
    - image: "ghcr.io/duobitx/yass/fs_engine_udp_ping"
      env:
        - name: param1
          value: "zzz"
        - name: param2
          value: "xydw"
        - name: HOST
          value: "sat-1"
  start: true
  simulationStartTime: "2025-10-06T14:35:00.123Z"

