apiVersion: int.esa.yass/v1
kind: Experiment
metadata:
  name: example-experiment
  namespace: default
spec:
  experimentDefRef: example-experimentdef
  layoutDefRef: example-layout
  engine:
    image: "ghcr.io/esa-philab/yass/fs_engine_udp_ping"
    configurationFilesFromConfigMap:
      mountPath: /some/directory
      configMapRef: "engine-configuration-config-map"
    envsMap:
      param1: "zzz"
      param2: "xydw"
      HOST: "sat-1"
  start: true
  simulationStartTime: "2025-10-06T14:35:00.123Z"

