apiVersion: int.esa.yass/v1
kind: HardwareDefinition
metadata:
  name: example-hwdef
spec:
  cpu: "200m"
  memory: "1Gi"
  diskSpace: "20G"
---
apiVersion: int.esa.yass/v1
kind: HardwareDefinition
metadata:
  name: ground-station-hwdef
spec:
  cpu: "2000m"
  memory: "4Gi"
  diskSpace: "20T"

